services:
  nginx:
    image: tiangolo/nginx-rtmp:latest #imagem usada com o protocolo rtmp de entrada de vídeo 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf #configurando pastas dentro do container
      - ./stream:/hls/live #recebe os dados da pasta /hls/live (container) e vai direto para a pasta stream 
    ports:
      - "1935:1935"
      - "8081:8081"